#############################################################################
# Makefile for building: src
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 20 15:48:25 2022
# Project:  src.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile src.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-control_lib \
		sub-control_gui

control_lib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) control_lib/ || $(MKDIR) control_lib/ 
	cd control_lib/ && $(QMAKE) /media/mikhail/AVGR/StreamProject/control_lib/control_lib.pro -o $(MAKEFILE)
sub-control_lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) control_lib/ || $(MKDIR) control_lib/ 
	cd control_lib/ && $(QMAKE) /media/mikhail/AVGR/StreamProject/control_lib/control_lib.pro -o $(MAKEFILE)
sub-control_lib: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE)
sub-control_lib-make_default-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) 
sub-control_lib-make_default: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) 
sub-control_lib-make_first-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) first
sub-control_lib-make_first: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) first
sub-control_lib-all-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) all
sub-control_lib-all: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) all
sub-control_lib-clean-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-control_lib-clean: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) clean
sub-control_lib-distclean-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-control_lib-distclean: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-control_lib-install_subtargets-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) install
sub-control_lib-install_subtargets: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) install
sub-control_lib-uninstall_subtargets-ordered: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-control_lib-uninstall_subtargets: control_lib//$(MAKEFILE) FORCE
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) uninstall
control_gui//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) control_gui/ || $(MKDIR) control_gui/ 
	cd control_gui/ && $(QMAKE) /media/mikhail/AVGR/StreamProject/control_gui/control_gui.pro -o $(MAKEFILE)
sub-control_gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) control_gui/ || $(MKDIR) control_gui/ 
	cd control_gui/ && $(QMAKE) /media/mikhail/AVGR/StreamProject/control_gui/control_gui.pro -o $(MAKEFILE)
sub-control_gui: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE)
sub-control_gui-make_default-ordered: control_gui//$(MAKEFILE) sub-control_lib-make_default-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) 
sub-control_gui-make_default: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) 
sub-control_gui-make_first-ordered: control_gui//$(MAKEFILE) sub-control_lib-make_first-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) first
sub-control_gui-make_first: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) first
sub-control_gui-all-ordered: control_gui//$(MAKEFILE) sub-control_lib-all-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) all
sub-control_gui-all: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) all
sub-control_gui-clean-ordered: control_gui//$(MAKEFILE) sub-control_lib-clean-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-control_gui-clean: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-control_gui-distclean-ordered: control_gui//$(MAKEFILE) sub-control_lib-distclean-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-control_gui-distclean: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-control_gui-install_subtargets-ordered: control_gui//$(MAKEFILE) sub-control_lib-install_subtargets-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) install
sub-control_gui-install_subtargets: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) install
sub-control_gui-uninstall_subtargets-ordered: control_gui//$(MAKEFILE) sub-control_lib-uninstall_subtargets-ordered  FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-control_gui-uninstall_subtargets: control_gui//$(MAKEFILE) FORCE
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: src.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile src.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile src.pro

qmake_all: sub-control_lib-qmake_all sub-control_gui-qmake_all FORCE

make_default: sub-control_lib-make_default-ordered sub-control_gui-make_default-ordered FORCE
make_first: sub-control_lib-make_first-ordered sub-control_gui-make_first-ordered FORCE
all: sub-control_lib-all-ordered sub-control_gui-all-ordered FORCE
clean: sub-control_lib-clean-ordered sub-control_gui-clean-ordered FORCE
distclean: sub-control_lib-distclean-ordered sub-control_gui-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-control_lib-install_subtargets-ordered sub-control_gui-install_subtargets-ordered FORCE
uninstall_subtargets: sub-control_lib-uninstall_subtargets-ordered sub-control_gui-uninstall_subtargets-ordered FORCE

sub-control_lib-check_ordered: control_lib/$(MAKEFILE)
	cd control_lib/ && $(MAKE) -f $(MAKEFILE) check
sub-control_gui-check_ordered: control_gui/$(MAKEFILE) sub-control_lib-check_ordered 
	cd control_gui/ && $(MAKE) -f $(MAKEFILE) check
check: sub-control_lib-check_ordered sub-control_gui-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

